language: php
os: linux

env:
  - DB_ADAPTER=mysql DB_NAME=dts DB_USER=root DB_HOST=127.0.0.1

php:
  - 8.2

matrix:
  fast_finish: false

install:
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

notifications:
  email:
    on_success: never
    on_failure: always

# cache composer for faster tests
cache:
  directories:
    - vendor
    - $HOME/.cache/composer
